### ISSUE TITLE
Add Multithreading

### ISSUE THREAD

**Issue by burnmine** [vinskasenda/DawnValidatorBot#1]
ada versi multithread nya bang? checker proxynya lama soalnya hehe

**Comment by vinskasenda** [comment]
lagi mau diupgrade, ditunggu ya

**Comment by vinskasenda** [comment]
> ada versi multithread nya bang? checker proxynya lama soalnya hehe

udah di update, silahkan git pull

**Comment by burnmine** [comment]
mantap bang, ty

> > ada versi multithread nya bang? checker proxynya lama soalnya hehe
> 
> udah di update, silahkan git pull
